import pandas as pd
import numpy as np
df = pd.read_csv('student_data.csv')
df['gender'] = df['gender'].str.lower().str.strip()
df['gender'] = df['gender'].replace({'m': 'male', 'f': 'female', 'fem': 'female', 'mal': 'male', 'na': np.nan, '-': np.nan})
df['gender'] = df['gender'].fillna('unknown')
df['department'] = df['department'].str.lower().str.strip()
df['department'] = df['department'].fillna('unknown')
df['scholarship'] = df['scholarship'].str.lower().str.strip()
df['scholarship'] = df['scholarship'].map({'y':1, 'yes':1, 'n':0, 'no':0, 'nope':0}).fillna(0)
df['parental_education'] = df['parental_education'].str.lower().str.strip()
df['parental_education'] = df['parental_education'].fillna('unknown')
df['extra_curricular'] = df['extra_curricular'].str.lower().str.strip()
df['extra_curricular'] = df['extra_curricular'].map({'y':1, 'yes':1, 'n':0, '-':0, 'no':0}).fillna(0)
median_age = df['age'].median()
df['age'] = df['age'].fillna(median_age)
median_cgpa = df['cgpa'].median()
df['cgpa'] = df['cgpa'].fillna(median_cgpa)
median_att = df['attendance_rate'].median()
df['attendance_rate'] = df['attendance_rate'].fillna(median_att)
median_pf = df['past_failures'].median()
df['past_failures'] = df['past_failures'].fillna(median_pf)
median_sh = df['study_hours_per_week'].median()
df['study_hours_per_week'] = df['study_hours_per_week'].fillna(median_sh)
df['sports_participation'] = df['sports_participation'].str.lower().str.strip()
df['sports_participation'] = df['sports_participation'].map({'y':1, 'yes':1, 'n':0, 'no':0}).fillna(0)
print(df.isnull().sum())
df.to_csv('student_data_cleaned.csv', index=False)
print(df.shape)
print(df.head())